import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

import streamlit as st


BASE_DIR = Path(__file__).resolve().parent
ENV_FILE = BASE_DIR / ".env"
MODELS_DIR = BASE_DIR / "models"
LOCAL_LLM_PATH = os.getenv("LOCAL_QWEN_GGUF_PATH", "").strip()
SENSEVOICE_MODEL = os.getenv("SENSEVOICE_MODEL", "iic/SenseVoiceSmall").strip()
VIDEO_SAMPLE_INTERVAL = int(os.getenv("VIDEO_SAMPLE_INTERVAL", "15"))
LLAMA_GPU_LAYERS = int(os.getenv("LLAMA_GPU_LAYERS", "0"))
LLAMA_N_CTX = int(os.getenv("LLAMA_N_CTX", "4096"))
AUTO_DOWNLOAD_MODEL = os.getenv("AUTO_DOWNLOAD_MODEL", "1").strip() or "1"
QWEN_MODEL_FILENAME = os.getenv("QWEN_MODEL_FILENAME", "Qwen3.5-4B-q5_k_m.gguf").strip() or "Qwen3.5-4B-q5_k_m.gguf"
QWEN_MODEL_DOWNLOAD_URL = os.getenv(
    "QWEN_MODEL_DOWNLOAD_URL",
    "https://huggingface.co/Smoffyy/Qwen3.5-4B-Instruct-Pure-GGUF/resolve/main/Qwen3.5-4B-q5_k_m.gguf?download=true",
).strip() or "https://huggingface.co/Smoffyy/Qwen3.5-4B-Instruct-Pure-GGUF/resolve/main/Qwen3.5-4B-q5_k_m.gguf?download=true"
SCORE_WEIGHTS = {
    "layer1_score": 0.40,
    "layer2_score": 0.30,
    "layer3_score": 0.30,
}


def parse_ai_json(content):
    if not content:
        raise json.JSONDecodeError("empty content", "", 0)

    cleaned = content.replace("```json", "").replace("```", "").strip()
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{[\s\S]*\}", cleaned)
        if not match:
            raise
        return json.loads(match.group(0))


def read_uploaded_text(uploaded_file):
    suffix = Path(uploaded_file.name).suffix.lower()
    data = uploaded_file.getvalue()

    if suffix in {".txt", ".md", ".csv", ".json"}:
        for encoding in ("utf-8", "utf-8-sig", "gbk"):
            try:
                return data.decode(encoding)
            except UnicodeDecodeError:
                continue
        return data.decode("utf-8", errors="ignore")

    if suffix == ".pdf":
        try:
            from pypdf import PdfReader
        except ImportError as exc:
            raise RuntimeError("缺少 pypdf，请先安装依赖") from exc

        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp_file:
            tmp_file.write(data)
            tmp_path = Path(tmp_file.name)

        try:
            reader = PdfReader(str(tmp_path))
            return "\n".join(page.extract_text() or "" for page in reader.pages)
        finally:
            tmp_path.unlink(missing_ok=True)

    if suffix == ".docx":
        try:
            from docx import Document
        except ImportError as exc:
            raise RuntimeError("缺少 python-docx，请先安装依赖") from exc

        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp_file:
            tmp_file.write(data)
            tmp_path = Path(tmp_file.name)

        try:
            document = Document(str(tmp_path))
            return "\n".join(paragraph.text for paragraph in document.paragraphs)
        finally:
            tmp_path.unlink(missing_ok=True)

    raise RuntimeError(f"不支持的简历格式：{suffix or '未知'}")


def save_runtime_config_to_env(model_path, sensevoice_model, sample_interval):
    model_path_value = normalize_model_path_for_env(model_path)
    lines = [
        "# Auto-generated by AI Recruit Demo",
        f"LOCAL_QWEN_GGUF_PATH={model_path_value}",
        f"AUTO_DOWNLOAD_MODEL={AUTO_DOWNLOAD_MODEL}",
        f"QWEN_MODEL_FILENAME={QWEN_MODEL_FILENAME}",
        f"QWEN_MODEL_DOWNLOAD_URL={QWEN_MODEL_DOWNLOAD_URL}",
        f"SENSEVOICE_MODEL={sensevoice_model}",
        f"VIDEO_SAMPLE_INTERVAL={sample_interval}",
        f"LLAMA_GPU_LAYERS={LLAMA_GPU_LAYERS}",
        f"LLAMA_N_CTX={LLAMA_N_CTX}",
        "",
    ]
    ENV_FILE.write_text("\n".join(lines), encoding="utf-8")


def normalize_model_path_for_env(model_path):
    model_file = Path(model_path)
    if not model_file.is_absolute():
        return str(model_file).replace("\\", "/")

    try:
        return str(model_file.resolve().relative_to(BASE_DIR)).replace("\\", "/")
    except Exception:
        return str(model_file).replace("\\", "/")


def get_runtime_local_config():
    st.subheader("本地模型配置")
    mode = st.radio(
        "配置方式",
        ["一键启动读取 .env", "手动输入（本次会话）"],
        horizontal=True,
    )
    st.session_state["config_mode"] = mode

    if mode == "一键启动读取 .env":
        model_path = LOCAL_LLM_PATH
        sensevoice_model = SENSEVOICE_MODEL
        sample_interval = VIDEO_SAMPLE_INTERVAL

        if model_path:
            st.success("已读取到 LOCAL_QWEN_GGUF_PATH。")
        else:
            st.warning("当前未配置 LOCAL_QWEN_GGUF_PATH，请切换到手动输入模式。")

        st.caption("综合得分固定权重：技能匹配 35%，成长潜力 25%，稳定性 20%，软性特质 20%。")

        return model_path, sensevoice_model, sample_interval

    model_path = st.text_input(
        "LOCAL_QWEN_GGUF_PATH",
        value=LOCAL_LLM_PATH,
        placeholder="例如：D:/models/Qwen-7B-Chat-Q4_K_M.gguf",
    ).strip()
    sensevoice_model = st.text_input(
        "SENSEVOICE_MODEL",
        value=SENSEVOICE_MODEL,
        placeholder="例如：iic/SenseVoiceSmall",
    ).strip()
    sample_interval = st.number_input(
        "视频抽帧间隔（帧）",
        min_value=1,
        max_value=120,
        value=VIDEO_SAMPLE_INTERVAL,
        step=1,
    )

    st.caption("手动输入仅对当前页面会话有效，保存后会写入项目根目录 .env。")
    return model_path, sensevoice_model, int(sample_interval)


def normalize_name_hint(value):
    if not value:
        return ""

    stem = Path(value).stem if Path(value).suffix else value
    stem = stem.lower()
    stem = re.sub(r"[\s_\-—–().【】\[\]{}<>]+", "", stem)
    stem = re.sub(r"(简历|resume|cv|视频|video|面试|interview|录屏|record|candidate|候选人|副本|final|draft)", "", stem)
    return stem


def extract_name_candidates(text):
    if not text:
        return []

    seen = []
    for token in re.findall(r"[\u4e00-\u9fff]{2,4}", text):
        if token not in seen and token not in {"简历", "岗位", "项目", "责任心", "学习能力", "团队协作"}:
            seen.append(token)
    for token in re.findall(r"[A-Za-z][A-Za-z0-9]{1,24}", text):
        if token not in seen:
            seen.append(token)
    return seen


def choose_candidate_name(resume_text, resume_filename, video_filename=None):
    resume_hints = extract_name_candidates(f"{resume_filename}\n{resume_text[:1200]}")
    video_hints = extract_name_candidates(video_filename or "")

    if video_hints:
        for resume_hint in resume_hints:
            resume_key = normalize_name_hint(resume_hint)
            for video_hint in video_hints:
                video_key = normalize_name_hint(video_hint)
                if resume_key and video_key and (
                    resume_key == video_key or resume_key in video_key or video_key in resume_key
                ):
                    return resume_hint, True

    if resume_hints:
        return resume_hints[0], bool(video_hints)

    return normalize_name_hint(resume_filename) or "未识别姓名", False


def match_video_for_resume(resume_filename, resume_text, video_files):
    resume_hints = [normalize_name_hint(item) for item in extract_name_candidates(f"{resume_filename}\n{resume_text[:1200]}")]
    resume_hints = [hint for hint in resume_hints if hint]

    best_match = None
    best_score = 0

    for video_file in video_files:
        video_hints = [normalize_name_hint(item) for item in extract_name_candidates(video_file.name)]
        video_hints = [hint for hint in video_hints if hint]

        score = 0
        for resume_hint in resume_hints:
            for video_hint in video_hints:
                if resume_hint == video_hint:
                    score = max(score, 3)
                elif resume_hint in video_hint or video_hint in resume_hint:
                    score = max(score, 2)
                elif resume_hint and video_hint and resume_hint[:2] == video_hint[:2]:
                    score = max(score, 1)

        if score > best_score:
            best_score = score
            best_match = video_file

    return best_match, best_score >= 2


def build_qwen_prompt(resume_text, job_requirement, candidate_name, video_context=None):
    video_block = video_context or "未提供视频或姓名无法匹配，按简历单独评分。"
    return f"""
你是一个专业的AI招聘评估助手，负责对候选人进行高潜人才筛选。

请根据岗位要求、简历内容，以及可用的视频辅助信息，输出严格JSON，不要输出任何解释文字。

评分要求：
1. Layer 1 硬技能层（40%）：学历背景、项目经验、技术能力
2. Layer 2 软技能层（30%）：沟通表达、逻辑思维、团队协作
3. Layer 3 潜力层（30%）：学习曲线、成长轨迹、内在动机、价值观匹配

综合匹配分会由程序按固定权重自动计算：
Layer 1 40%，Layer 2 30%，Layer 3 30%

输出格式：
{{
  "candidate_name": "姓名",
    "layer1_score": 0.0-10.0,
    "layer2_score": 0.0-10.0,
    "layer3_score": 0.0-10.0,
    "total_score": 0.0-10.0,
  "level": "S/A/B/C",
  "summary": "一句话总结",
  "risk_points": ["风险点1", "风险点2"],
  "match_basis": ["依据1", "依据2"]
}}

候选人姓名：{candidate_name}

岗位要求：
{job_requirement}

简历内容：
{resume_text}

视频辅助信息：
{video_block}
""".strip()


def sanitize_accel_env_for_llama_cpp():
    # llama-cpp on Windows will add CUDA/HIP dll dirs if env vars exist.
    # Remove stale paths to avoid FileNotFoundError during import.
    for key in ("CUDA_PATH", "HIP_PATH"):
        root = os.getenv(key, "").strip()
        if not root:
            continue

        root_path = Path(root)
        if not root_path.exists():
            os.environ.pop(key, None)
            continue

        if not (root_path / "bin").exists() and not (root_path / "lib").exists():
            os.environ.pop(key, None)


def normalize_score_value(value):
    try:
        numeric_value = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"无效分数：{value}") from exc

    return round(max(0.0, min(10.0, numeric_value)), 1)

def calculate_weighted_total_score(parsed):
    total_score = 0.0
    for key, weight in SCORE_WEIGHTS.items():
        total_score += normalize_score_value(parsed[key]) * weight
    return round(total_score, 1)

def normalize_score_fields(parsed):
    for key in ("layer1_score", "layer2_score", "layer3_score"):
        parsed[key] = normalize_score_value(parsed[key])
    parsed["total_score"] = calculate_weighted_total_score(parsed)
    return parsed


@st.cache_resource(show_spinner=False)
def load_qwen_llm(model_path):
    if not model_path:
        raise RuntimeError("未配置 LOCAL_QWEN_GGUF_PATH。")

    model_file = Path(model_path)
    if not model_file.exists():
        raise FileNotFoundError(f"找不到本地模型文件：{model_file}")

    sanitize_accel_env_for_llama_cpp()

    try:
        from llama_cpp import Llama
    except ImportError as exc:
        raise RuntimeError("缺少 llama-cpp-python，请先安装依赖") from exc

    return Llama(
        model_path=str(model_file),
        n_ctx=LLAMA_N_CTX,
        n_gpu_layers=LLAMA_GPU_LAYERS,
        verbose=False,
    )


def analyze_candidate_with_qwen(resume_text, job_requirement, candidate_name, model_path, video_context=None):
    llm = load_qwen_llm(model_path)
    prompt = build_qwen_prompt(resume_text, job_requirement, candidate_name, video_context)

    try:
        result = llm.create_chat_completion(
            messages=[
                {"role": "system", "content": "你只输出合法JSON，不要输出多余文字。"},
                {"role": "user", "content": prompt},
            ],
            temperature=0.1,
            max_tokens=768,
        )
        content = result["choices"][0]["message"]["content"]
        parsed = parse_ai_json(content)
    except Exception as exc:
        st.error(f"本地 Qwen 调用失败：{exc}")
        return None

    required_keys = [
        "candidate_name",
        "layer1_score",
        "layer2_score",
        "layer3_score",
        "total_score",
        "level",
        "summary",
        "risk_points",
        "match_basis",
    ]
    if not all(key in parsed for key in required_keys):
        st.error(f"Qwen 返回 JSON 字段不完整：{parsed}")
        return None

    try:
        return normalize_score_fields(parsed)
    except ValueError as exc:
        st.error(f"Qwen 返回分数字段格式错误：{exc}")
        return None


def store_upload_to_temp(uploaded_file):
    suffix = Path(uploaded_file.name).suffix or ".bin"
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp_file:
        tmp_file.write(uploaded_file.getvalue())
        return Path(tmp_file.name)


def extract_audio_with_ffmpeg(video_path):
    if not shutil.which("ffmpeg"):
        return None

    audio_handle = tempfile.NamedTemporaryFile(delete=False, suffix=".wav")
    audio_handle.close()
    audio_path = Path(audio_handle.name)

    command = [
        "ffmpeg",
        "-y",
        "-i",
        str(video_path),
        "-vn",
        "-ac",
        "1",
        "-ar",
        "16000",
        str(audio_path),
    ]
    completed = subprocess.run(command, capture_output=True, text=True)
    if completed.returncode != 0 or not audio_path.exists():
        audio_path.unlink(missing_ok=True)
        return None

    return audio_path


def transcribe_with_sensevoice(video_path, model_name):
    audio_path = extract_audio_with_ffmpeg(video_path)
    if not audio_path:
        return ""

    try:
        from funasr import AutoModel
    except ImportError:
        audio_path.unlink(missing_ok=True)
        return ""

    try:
        asr_model = AutoModel(model=model_name, disable_update=True)
        output = asr_model.generate(input=str(audio_path))
    except Exception:
        audio_path.unlink(missing_ok=True)
        return ""
    finally:
        audio_path.unlink(missing_ok=True)

    transcript = ""
    if isinstance(output, list) and output:
        first_item = output[0]
        if isinstance(first_item, dict):
            transcript = first_item.get("text") or first_item.get("sentence") or first_item.get("preds") or ""
        else:
            transcript = str(first_item)
    elif isinstance(output, dict):
        transcript = output.get("text") or output.get("sentence") or output.get("preds") or ""
    else:
        transcript = str(output)

    return transcript.strip()


def summarize_face_mesh(video_path, sample_interval):
    try:
        import cv2
        import mediapipe as mp
    except ImportError:
        return "FaceMesh 不可用：缺少 mediapipe 或 opencv-python。"

    capture = cv2.VideoCapture(str(video_path))
    if not capture.isOpened():
        return "视频无法打开。"

    frame_count = 0
    sampled_count = 0
    face_count = 0
    center_motion = []
    mouth_motion = []
    eye_opening = []
    previous_center = None

    with mp.solutions.face_mesh.FaceMesh(
        static_image_mode=False,
        refine_landmarks=True,
        max_num_faces=1,
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5,
    ) as face_mesh:
        while True:
            ok, frame = capture.read()
            if not ok:
                break

            if frame_count % sample_interval != 0:
                frame_count += 1
                continue

            sampled_count += 1
            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            result = face_mesh.process(rgb_frame)
            if not result.multi_face_landmarks:
                frame_count += 1
                continue

            face_count += 1
            landmarks = result.multi_face_landmarks[0].landmark
            xs = [point.x for point in landmarks]
            ys = [point.y for point in landmarks]
            center = ((min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2)

            if previous_center is not None:
                center_motion.append(abs(center[0] - previous_center[0]) + abs(center[1] - previous_center[1]))
            previous_center = center

            mouth_motion.append(abs(landmarks[13].y - landmarks[14].y))
            eye_opening.append(
                (
                    abs(landmarks[159].y - landmarks[145].y)
                    + abs(landmarks[386].y - landmarks[374].y)
                )
                / 2
            )

            frame_count += 1

    capture.release()

    if sampled_count == 0:
        return "未采样到有效视频帧。"

    detection_ratio = face_count / sampled_count
    avg_center_motion = sum(center_motion) / len(center_motion) if center_motion else 0.0
    avg_mouth_motion = sum(mouth_motion) / len(mouth_motion) if mouth_motion else 0.0
    avg_eye_opening = sum(eye_opening) / len(eye_opening) if eye_opening else 0.0

    return (
        f"FaceMesh统计：采样帧数={sampled_count}，有人脸帧数={face_count}，"
        f"人脸出现率={detection_ratio:.2f}，头部中心位移均值={avg_center_motion:.4f}，"
        f"嘴部变化均值={avg_mouth_motion:.4f}，眼部开合均值={avg_eye_opening:.4f}。"
    )


def build_video_context(video_path, sample_interval, sensevoice_model):
    face_summary = summarize_face_mesh(video_path, sample_interval)
    transcript = transcribe_with_sensevoice(video_path, sensevoice_model)

    blocks = [f"FaceMesh摘要：{face_summary}"]
    if transcript:
        blocks.append(f"SenseVoiceSmall转写：{transcript}")
    else:
        blocks.append("SenseVoiceSmall转写：未提取到有效语音，保留 FaceMesh 结果作为视频辅助信息。")
    return "\n".join(blocks)


st.set_page_config(page_title="AI高潜人才筛选Demo", page_icon="🤖", layout="wide")

st.title("🤖 AI 高潜人才智能筛选辅助系统")
st.caption("本地版 | 简历使用 Qwen-7B 4bit，视频使用 MediaPipe FaceMesh + SenseVoiceSmall")

col_left, col_right = st.columns(2)

with col_left:
    st.subheader("📄 批量简历文件")
    resume_files = st.file_uploader(
        "上传简历文件",
        type=["txt", "md", "pdf", "docx"],
        accept_multiple_files=True,
        help="建议文件名包含候选人姓名，例如 张三_简历.pdf",
    )

with col_right:
    st.subheader("🎥 批量视频文件")
    video_files = st.file_uploader(
        "上传视频文件",
        type=["mp4", "mov", "mkv", "avi", "webm"],
        accept_multiple_files=True,
        help="建议文件名包含候选人姓名，例如 张三_面试视频.mp4",
    )

st.subheader("🎯 岗位要求")
job_requirement = st.text_area(
    "粘贴岗位要求",
    height=200,
    value="要求：数据分析能力、项目经验、学习能力强、沟通协作好、稳定性高。",
)

llm_model_path, sensevoice_model, sample_interval = get_runtime_local_config()

if st.session_state.get("config_mode") == "手动输入（本次会话）":
    save_col1, save_col2 = st.columns([1, 2])
    with save_col1:
        save_clicked = st.button("💾 保存到 .env")
    with save_col2:
        st.caption("保存后，下次一键启动会自动读取这些本地模型配置。")

    if save_clicked:
        if not llm_model_path:
            st.error("请先填写 LOCAL_QWEN_GGUF_PATH，再保存到 .env。")
        else:
            try:
                save_runtime_config_to_env(llm_model_path, sensevoice_model, sample_interval)
                st.success(f"已保存到 {ENV_FILE.name}。")
            except Exception as exc:
                st.error(f"保存 .env 失败：{exc}")


if st.button("🚀 开始批量分析"):
    if not resume_files:
        st.warning("请至少上传一个简历文件。")
    elif not llm_model_path:
        st.error("请先配置本地 Qwen 4bit 模型路径。")
    else:
        results = []

        for resume_file in resume_files:
            try:
                resume_text = read_uploaded_text(resume_file)
            except Exception as exc:
                results.append(
                    {
                        "candidate_name": normalize_name_hint(resume_file.name) or resume_file.name,
                        "status": f"简历读取失败：{exc}",
                        "resume_file": resume_file.name,
                        "video_file": "",
                        "total_score": "-",
                    }
                )
                continue

            matched_video, name_matched = match_video_for_resume(resume_file.name, resume_text, video_files or [])
            candidate_name, _ = choose_candidate_name(
                resume_text,
                resume_file.name,
                matched_video.name if matched_video else None,
            )

            with st.spinner(f"正在分析：{candidate_name}"):
                video_context = None
                if matched_video and name_matched:
                    try:
                        video_path = store_upload_to_temp(matched_video)
                        try:
                            video_context = build_video_context(video_path, sample_interval, sensevoice_model)
                        finally:
                            video_path.unlink(missing_ok=True)
                    except Exception as exc:
                        video_context = f"视频分析失败，已退化为简历单独评分。失败原因：{exc}"

                ai_result = analyze_candidate_with_qwen(
                    resume_text=resume_text,
                    job_requirement=job_requirement,
                    candidate_name=candidate_name,
                    model_path=llm_model_path,
                    video_context=video_context,
                )

            if not ai_result:
                results.append(
                    {
                        "candidate_name": candidate_name,
                        "status": "分析失败",
                        "resume_file": resume_file.name,
                        "video_file": matched_video.name if matched_video and name_matched else "未匹配",
                        "total_score": "-",
                    }
                )
                continue

            results.append(
                {
                    **ai_result,
                    "status": "成功",
                    "resume_file": resume_file.name,
                    "video_file": matched_video.name if matched_video and name_matched else "未匹配，仅简历评分",
                    "name_matched": "是" if matched_video and name_matched else "否",
                }
            )

        if results:
            st.subheader("📊 批量评估结果")
            st.dataframe(results, use_container_width=True)

            for item in results:
                title = f"{item.get('candidate_name', '未知候选人')} | {item.get('level', item.get('status', '结果'))}"
                with st.expander(title):
                    st.write(f"简历文件：{item.get('resume_file', '')}")
                    st.write(f"视频文件：{item.get('video_file', '')}")
                    st.write(f"姓名匹配：{item.get('name_matched', item.get('status', ''))}")
                    if item.get("status") == "成功":
                        left_col, right_col = st.columns(2)
                        with left_col:
                            st.metric("Layer 1 硬技能层", f"{item['layer1_score']:.1f}/10")
                            st.metric("Layer 2 软技能层", f"{item['layer2_score']:.1f}/10")
                        with right_col:
                            st.metric("Layer 3 潜力层", f"{item['layer3_score']:.1f}/10")
                            st.metric("综合得分", f"{item['total_score']:.1f}/10")
                            st.metric("等级", item['level'])

                        st.write(f"总结：{item.get('summary', '')}")
                        st.write("风险点：")
                        st.write(item.get("risk_points", []))
                        st.write("匹配依据：")
                        st.write(item.get("match_basis", []))
                    else:
                        st.error(item.get("status", "失败"))


st.divider()
st.caption("姓名匹配规则：优先按文件名和简历内容提取候选人姓名，匹配成功时融合视频辅助信息；匹配失败则仅按简历打分。")